version: '3.9'

services:
  estudo-back:
    build: 
      context: .
    ports:
      - '8082:3000'
    networks:
      - estudo-rede
    restart: on-failure
    command: bash -c "npm run knex && npm run start"
    depends_on:
      - mysql
    links: 
      - mysql
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password
    container_name: estudo-banco
    networks:
      - estudo-rede

volumes:
  mysql:
    driver: local
networks:
  estudo-rede:
    driver: bridge