version: '3'

services:
  estudo-back:
    build: 
      context: .
    ports:
      - '8081:3000'
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql:
    driver: local